# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: locharve <locharve@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/11/15 10:02:00 by locharve          #+#    #+#              #
#    Updated: 2024/12/02 15:42:41 by locharve         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = asterix
SRC = main.cpp Bureaucrat.cpp AForm.cpp ShrubberyCreationForm.cpp

include ../ex00/Makefile